[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino

[env:native]
platform = native
build_src_filter = +<../lib/DCCRailcom> +<../test>
lib_archive = no
lib_deps =
  fabiobatsilva/ArduinoFake
  throwtheswitch/Unity
