[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino

[env:native]
platform = native
build_flags = -I lib/DCCRailcom
lib_deps =
  file://.
  fabiobatsilva/ArduinoFake
  throwtheswitch/Unity
